name: Produce from Twitter and Consume to Telegram

# Controls when the workflow will run
on:
  
  schedule:
  - cron: '0 */3 * * *'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  produce:
    runs-on: ubuntu-latest
    environment: alembik
    container:
      image: ghcr.io/gabrielepicco/alembik/alembik-producer
      credentials:
         username: ${{ github.actor }}
         password: ${{ secrets.GHCR_TOKEN }}
      env:
        SOURCE: twitter
        ACCOUNT: Magicblock
        MONGO_HOST: ${{ secrets.MONGO_HOST }}
        MONGO_DB: alembik
        USE_DEEP_LEARNING: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-docker-${{ hashFiles('**/Dockerfile') }}
          restore-keys: |
            ${{ runner.os }}-docker-
      - name: Login to GitHub Container Registry
        run: echo ${{ secrets.GHCR_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Pull Docker Image
        run: docker pull ghcr.io/gabrielepicco/alembik/alembik-producer
      - name: Load Cached Docker Layers
        run: |
          mkdir -p /tmp/.buildx-cache
          docker save mongo | tar xf - -C /tmp/.buildx-cache
      - name: Download nltk lang
        working-directory: /app
        run: python -c "import nltk;nltk.download('punkt')"
      - name: Produce
        working-directory: /app
        run: python -m alembik
